Default to Python 3
This also fixes my

  TypeError: Couldn't find foreign struct converter for 'cairo.Context'

because I apparently did not have python-gi-cairo installed (but I did
have python3-gi-cairo).