Fix TypeError when monitored process dies
The error was

  TypeError: process_exited() takes 2 positional arguments but 3 were given

and it got introduced when I switched from using custom signals to using
notify::alive.